# .github/actions/k8s-setup/action.yml
name: 'Setup Kubernetes Tools'
description: 'Sets up Helm, kubectl, and authenticates with GKE'

inputs:
  helm-version:
    description: 'Version of Helm to install'
    required: true
  gcp-credentials:
    description: 'GCP Service Account Key'
    required: true
  gcp-project-id:
    description: 'GCP Project ID'
    required: true
  cluster-name:
    description: 'GKE Cluster Name'
    required: true
  cluster-zone:
    description: 'GKE Cluster Zone'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: ${{ inputs.helm-version }}

    - name: Google Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ inputs.gcp-credentials }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Install kubectl and gke-auth
      shell: bash
      run: |
        gcloud components install kubectl gke-gcloud-auth-plugin
        gcloud --quiet auth configure-docker

    - name: Get GKE Credentials
      shell: bash
      run: |
        gcloud container clusters get-credentials ${{ inputs.cluster-name }} \
        --zone ${{ inputs.cluster-zone }} \
        --project ${{ inputs.gcp-project-id }}

    - name: Add Helm Repositories
      shell: bash
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo update
