apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "imdb-clone.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: NODE_ENV
              value: {{ .Values.global.environment | quote }}
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_URL
            - name: FRONTEND_DOMAIN
              value: {{ .Values.frontend.domain | quote }}
          readinessProbe:
            httpGet:
              path: /api/health/ready
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /api/health/live
              port: 5000
            initialDelaySeconds: 25
            periodSeconds: 30
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
