a# templates/backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: TCP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: backend

