---
# templates/configmaps.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: {{ .Values.global.namespace }}
data:
  MONGODB_INITDB_DATABASE: {{ .Values.mongodb.database }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-headers
  namespace: {{ .Values.global.namespace }}
data:
  X-Real-IP: "$remote_addr"
  X-Forwarded-For: "$proxy_add_x_forwarded_for"
